[settings]
experimental = true
trusted_config_paths = [
  "~/code/"
]

[tools]
bun = "latest"
github-cli = "latest"
"github:metruzanca/bj" = "latest"
"cargo:worktrunk" = "latest"
"npm:degit" = "latest"
"npm:kill-port" = "latest"
node = "latest"
