[window]
opacity = 1
# decorations = "None" # Disabling this on MacOS will prevent the window from having tabs.
startup_mode = "Maximized"

[font]
size = 16.0
normal = { family = "FiraCode Nerd Font" }

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]